package com.august.viiin.util

object Keywords {
    val data = setOf(
    "wine",
    "red wine",
    "white wine",
    "rosé",
    "sparkling",
    "sparkling wine",
    "champagne",
    "cabernet",
    "cabernet sauvignon",
    "merlot",
    "pinot",
    "pinot noir",
    "pinot grigio",
    "pinot gris",
    "chardonnay",
    "zinfandel",
    "syrah",
    "shiraz",
    "malbec",
    "sauvignon blanc",
    "riesling",
    "tempranillo",
    "nebbiolo",
    "barbera",
    "grenache",
    "sangiovese",
    "muscat",
    "moscato",
    "gewürztraminer",
    "petite sirah",
    "carignan",
    "mourvèdre",
    "torrontés",
    "grüner veltliner",
    "viognier",
    "ice wine",
    "port",
    "sherry",
    "vermouth",
    "madeira",
    "marsala",
    "lambrusco",
    "bordeaux",
    "burgundy",
    "chianti",
    "prosecco",
    "cava",
    "rioja",
    "vintage",
    "blend",
    "winemaker",
    "vineyard",
    "wineries",
    "table wine",
    "natural wine",
    "organic wine",
    "biodynamic wine",
    "aged wine",
    "cellared",
    "oak-aged",
    "barrel-aged",
    "fermented",
    "dry wine",
    "sweet wine",
    "semi-sweet",
    "medium dry",
    "crisp",
    "tannin",
    "body",
    "nose",
    "bouquet",
    "finish",
    "decant",
    "cork",
    "corked",
    "bottle",
    "glass",
    "terroir",
    "appellation",
    "estate",
    "viticulture",
    "oenology",
    "sommelier",
    "tasting notes",
    "wine tasting",
    "wine shop",
    "wine cellar",
    "wine rack",
    "wine glass",
    "wine bottle",
    "wine bar",
    "wine list",
    "alcohol",
    "grape",
    "grapes",
    "grape varietal",
    "wine country",
    "wine region",
    "winery",
    "old vine",
    "new world",
    "old world",
    "bubbly",
    "vin",
    "vino",
    "vintage wine"
    )

    val dataTokens: Set<String> by lazy {
        data.flatMap { it.lowercase().split(Regex("\\W+")) }.toSet()
    }
}